/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3132",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#410001",
        "primary-container": "#22c55e",
        "surface-dim": "#d9dadb",
        "on-secondary-fixed-variant": "#145126",
        "secondary": "#2f6a3c",
        "secondary-fixed": "#b2f2b7",
        "surface-container-low": "#f3f4f5",
        "surface": "#f8f9fa",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#ffdad5",
        "secondary-container": "#afefb4",
        "inverse-on-surface": "#f0f1f2",
        "outline": "#6d7b6c",
        "on-secondary-fixed": "#002109",
        "outline-variant": "#bccbb9",
        "surface-bright": "#f8f9fa",
        "tertiary-container": "#ff8b7c",
        "surface-container": "#edeeef",
        "secondary-fixed-dim": "#96d59d",
        "on-primary-fixed-variant": "#005321",
        "on-error": "#ffffff",
        "background": "#f8f9fa",
        "on-tertiary-fixed-variant": "#7f2a21",
        "tertiary-fixed-dim": "#ffb4a9",
        "on-tertiary-container": "#76231b",
        "surface-tint": "#006e2f",
        "on-surface": "#191c1d",
        "surface-container-high": "#e7e8e9",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#4ae176",
        "tertiary": "#9e4036",
        "surface-variant": "#e1e3e4",
        "on-primary-container": "#004b1e",
        "inverse-primary": "#4ae176",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#346e40",
        "on-primary-fixed": "#002109",
        "on-error-container": "#93000a",
        "primary": "#006e2f",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#3d4a3d",
        "error": "#ba1a1a",
        "surface-container-highest": "#e1e3e4",
        "primary-fixed": "#6bff8f",
        "on-background": "#191c1d"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "2xl": "1rem", "3xl": "1.5rem", "full": "9999px"},
    },
  },
  plugins: [],
}
